import "reflect-metadata";
import { Container } from "inversify";
import { FirebaseService } from "./services/FirebaseService";
import { UserService } from "./services/UserService";
import { ChatService } from "./services/ChatService";
import { AuthService } from "./services/AuthService";
import { MessageService } from "./services/MessageService";
import { MessageProcessingService } from "./services/MessageProcessingService";
import { AnthropicClient } from "./clients/AnthropicClient";
import { ToolExecutionService } from "./services/ToolExecutionService";
import { AICommitService } from "./services/AICommitService";
import { CommitWorkflowOrchestrator } from "./services/CommitWorkflowOrchestrator";
import { PromptBuilderService } from "./services/PromptBuilderService";
import { UsageTrackingService } from "./services/UsageTrackingService";
import { PlanLimitsService } from "./services/PlanLimitsService";
import { ResponseHandler } from "./services/ResponseHandler";
import { ToolExecutionCoordinator } from "./services/ToolExecutionCoordinator";
import { WorkflowStateManager } from "./services/WorkflowStateManager";
import { HotPayClient } from "./clients/HotPayClient";
import { PaymentService } from "./services/PaymentService";
import { SystemUserService } from "./services/SystemUserService";
const container = new Container();
container.bind(FirebaseService).toSelf().inSingletonScope();
container.bind(UserService).toSelf().inSingletonScope();
container.bind(ChatService).toSelf().inSingletonScope();
container.bind(AuthService).toSelf().inSingletonScope();
container.bind(MessageService).toSelf().inSingletonScope();
container.bind(MessageProcessingService).toSelf().inSingletonScope();
container.bind(AnthropicClient).toSelf().inSingletonScope();
container.bind(ToolExecutionService).toSelf().inSingletonScope();
container.bind(PromptBuilderService).toSelf().inSingletonScope();
container.bind(CommitWorkflowOrchestrator).toSelf().inSingletonScope();
container.bind(AICommitService).toSelf().inSingletonScope();
container.bind(UsageTrackingService).toSelf().inSingletonScope();
container.bind(PlanLimitsService).toSelf().inSingletonScope();
container.bind(ResponseHandler).toSelf().inSingletonScope();
container.bind(ToolExecutionCoordinator).toSelf().inSingletonScope();
container.bind(WorkflowStateManager).toSelf().inSingletonScope();
container.bind(HotPayClient).toSelf().inSingletonScope();
container.bind(PaymentService).toSelf().inSingletonScope();
container.bind(SystemUserService).toSelf().inSingletonScope();
export { container };
